GET http://localhost:8080/secured/status
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqaWxsQGV4YW1wbGUuY29tIiwibmJmIjoxNjM0MDU5NzE2LCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaXNzIjoibW4tamRiYy1hdXRoIiwibGFuZ3VhZ2UiOiJlbiIsImV4cCI6MTYzNDA2MzMxNiwiaWF0IjoxNjM0MDU5NzE2LCJoYWlyX2NvbG9yIjoiYnJvd24ifQ.XYlVOrqV4HHKkIyd84eDNJd4Nlh6WZ1oruKDYICdx5o